{{- range $i, $n := until (int .Values.replicas) }}
{{- if lt $i (len $.Values.service.swarm) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" $ }}-swarm-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ipfs.labels" $ | nindent 4 }}
    app.kubernetes.io/component: ipfs-peer
spec:
  type: {{ (index $.Values.service.swarm $i).type }}
  ports:
    - port: {{ (index $.Values.service.swarm $i).port }}
      targetPort: swarm
      protocol: TCP
      name: swarm
  {{- if (index $.Values.service.swarm $i).ipAddress }}
  loadBalancerIP: {{ (index $.Values.service.swarm $i).ipAddress | quote }}
  {{- end }}
  selector:
    {{- include "ipfs.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: ipfs-peer
    {{- if ne (int $.Values.replicas) 1 }}
    statefulset.kubernetes.io/pod-name: {{ include "ipfs.fullname" $ }}-{{ $i }}
    {{- end }}
{{- end }}
{{- end }}
