VERSION 0.6

ARG helmhelper=github.com/eniblock/build/helm:4.1
IMPORT $helmhelper AS helm

ARG repository=ghcr.io/eniblock/ipfs

deps:
    DO helm+BASE
    DO helm+UPDATE --helmdir=./ipfs

lint:
    FROM +deps
    COPY ipfs ./
    RUN lint ipfs ./ --values values-dev.yaml

build:
    FROM +deps
    ARG tag=0.1.0-local
    DO helm+BUILD --helmdir=./ipfs --patch_app_version=false --tag=${tag}
    SAVE ARTIFACT /app/*-${tag}.tgz

save-package:
    FROM scratch
    COPY +build/*.tgz /
    SAVE ARTIFACT /*.tgz AS LOCAL ./

publish:
    ARG tag=0.1.0-local
    FROM +build --tag=${tag}
    DO helm+LOGIN
    DO helm+PUBLISH --repository=$repository
